version: "3.9"

services:
  front-end:
    build:
        context: ./day-trading-app
    container_name: front-end
    ports:
      - "3000:3000"
  
  back-end:
    build:
        context: ./backend
    container_name: back-end
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development