version: "3.9"

services:
  clean-mongo:
    build:
      context: ./backend/config
    container_name: clean-mongo
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network
  
  auth-service:
    build:
      context: ./backend/auth
    deploy:
      replicas: 20
      endpoint_mode: vip
    volumes:
      - ./backend/auth:/server/auth
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  transaction-service:
    build:
        context: ./backend/transaction
    deploy:
      replicas: 20
      endpoint_mode: vip
    volumes:
      - ./backend/transaction:/server/transaction
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./backend/order
    deploy:
      replicas: 20
      endpoint_mode: vip
    volumes:
      - ./backend/order:/server/order
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  usermanagement-service:
    build:
      context: ./backend/userManagement
    deploy:
      replicas: 20
      endpoint_mode: vip
    volumes:
      - ./backend/userManagement:/server/userManagement
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: nginx:latest
    deploy:
      replicas: 3   # Multiple instances of Nginx
      endpoint_mode: vip
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      order-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      transaction-service:
        condition: service_healthy
      usermanagement-service:
        condition: service_healthy
    networks:
      - backend-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"    # Exposing Load Balancer on port 80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api-gateway
    networks:
      - backend-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - backend-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./backend/config/redis.conf:/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  matching-engine:
    ports:
      - "3006:3006"
    build:
      context: ./backend/matchingEngine
    container_name: matching-engine
    volumes:
      - ./backend/matchingEngine:/server/matchingEngine
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  backend-network:
    driver: bridge
