version: "3.9"

services:
  front-end:
    build:
      context: ./day-trading-app
    container_name: front-end
    ports:
      - "3000:3000"
    networks:
      - backend-network
  
  auth-service:
    build:
      context: ./backend/auth
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  order-service:
    build:
      context: ./backend/order
    container_name: order-service
    volumes:
      - ./backend/middleware:/backend/middleware
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  usermanagement-service:
    build:
      context: ./backend/userManagement
    container_name: usermanagement-service
    volumes:
      - ./backend/middleware:/backend/middleware
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"  # API Gateway is exposed on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - order-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
