version: "3.9"

services:
  clean-mongo:
    build:
      context: ./backend/config
    container_name: clean-mongo
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  front-end:
    build:
      context: ./day-trading-app
    container_name: front-end
    ports:
      - "3000:3000"
    networks:
      - backend-network
  
  auth-service-1:
    build:
      context: ./backend/auth
    container_name: auth-service-1
    ports:
      - "30011:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  auth-service-2:
    build:
      context: ./backend/auth
    container_name: auth-service-2
    ports:
      - "30012:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  transaction-service-1:
    build:
      context: ./backend/transaction
    container_name: transaction-service-1
    ports:
      - "30041:3004"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  transaction-service-2:
    build:
      context: ./backend/transaction
    container_name: transaction-service-2
    ports:
      - "30042:3004"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  order-service-1:
    build:
      context: ./backend/order
    container_name: order-service-1
    ports:
      - "30021:3002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - transaction-service-1
      - transaction-service-2
    networks:
      - backend-network

  order-service-2:
    build:
      context: ./backend/order
    container_name: order-service-2
    ports:
      - "30022:3002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - transaction-service-1
      - transaction-service-2
    networks:
      - backend-network

  order-service-3:
    build:
      context: ./backend/order
    container_name: order-service-3
    ports:
      - "30023:3002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - transaction-service-1
      - transaction-service-2
    networks:
      - backend-network
  usermanagement-service-1:
    build:
      context: ./backend/userManagement
    container_name: usermanagement-service-1
    ports:
      - "30031:3003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  usermanagement-service-2:
    build:
      context: ./backend/userManagement
    container_name: usermanagement-service-2
    ports:
      - "30032:3003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"  # API Gateway is exposed on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service-1
      - auth-service-2
      - transaction-service-1
      - transaction-service-2
      - order-service-1
      - order-service-2
      - usermanagement-service-1
      - usermanagement-service-2
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
