version: "3.9"

services:
  front-end:
    build:
      context: ./day-trading-app
    container_name: front-end
    ports:
      - "3000:3000"
    networks:
      - backend-network
  
  auth-service:
    build:
      context: ./backend/auth
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - backend-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"  # API Gateway is exposed on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
    depends_on:
      - auth-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"