name: Backend CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  set-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

  install-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run docker compose
      env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: docker-compose -f docker-compose.yml up --build -d --abort-on-container-exit

  install-jmeter:
    runs-on: ubuntu-latest
    steps:
    - name: Install jmeter
      run: sudo apt-get install jmeter
    
  test:
    runs-on: ubuntu-latest

    steps: 
    - name: Run sample_test_script2
      run: jmeter -n -t ./Sample_test_script2.jmx -l sample_test_script2.jtl
    
    - name: Verify test results
      run: cat sample_test_script2.jtl

    - name: Make sure test passed
      run: grep -q "false" sample_test_script2.jtl && exit 1 || exit 0
    
    - name: Stop docker compose
      run: docker-compose -f docker-compose.test.yml down